version: '3.8'

services:
  app:
    build: .
    container_name: go_app_container
    restart: always
    depends_on:
      - mariadb
      - mongo
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: beer_db
      DB_USER: user
      DB_PASSWORD: userpassword
      MONGO_URI: mongodb://mongo:27017/beer_logs
    ports:
      - "8080:8080"
    command: ["./main", "migrate"]

  mariadb:
    image: mariadb:10.5
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: beer_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"


  mongo:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mariadb_data:
  mongo_data:
